<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    // Récupérer le joueur sur une game active
    public function getCurrentPlayerInGame($fingerprint)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->leftJoin('a.game', 'game')
            ->where('a.fingerprint = :fingerprint')
            ->setParameter('fingerprint', $fingerprint)
            ->andWhere('game.isFinished = 0 OR game.isFinished is null')
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
