NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

games:
    type:     rest
    resource: AppBundle\Controller\GameController

players:
    type:     rest
    resource: AppBundle\Controller\PlayerController

questions:
    type:     rest
    resource: AppBundle\Controller\QuestionController

answers:
    type:     rest
    resource: AppBundle\Controller\AnswerController