#File use to avoid this error : A circular reference has been detected (configured limit: 1)

AppBundle\Entity\Game:
    attributes:
        id:
            groups: ['game', player]
        code:
            groups: ['game', player]
        nbPlayerMin:
            groups: ['game']
        nbPlayerMax:
            groups: ['game']
        description:
            groups: ['game']
        isStarted:
            groups: ['game']
        isFinished:
            groups: ['game']
        players:
            groups: ['game']
        questions:
            groups: ['game']
        currentQuestion:
            groups: ['game']

AppBundle\Entity\Player:
    attributes:
        id:
            groups: ['player', game]
        name:
            groups: ['player', game]
        fingerprint:
            groups: ['player', game]
        owner:
            groups: ['player', game]
        score:
            groups: ['player', game]
        game:
            groups: ['player']

AppBundle\Entity\Question:
    attributes:
        id:
            groups: ['question', answer]
        question:
            groups: ['question', answer]
        answers:
            groups: ['question']

AppBundle\Entity\Answer:
    attributes:
        id:
            groups: ['answer', question]
        answer:
            groups: ['answer', question]
        goodAnswer:
            groups: ['answer', question]
        question:
            groups: ['answer']